name: Build JSON Outputs

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipelines
        run: python run_all.py

      - name: Upload artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: json-results
          path: dist/

      - name: Commit JSON results back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@users.noreply.github.com"
          git add dist/*.json || true
          git diff --cached --quiet || git commit -m "Update JSON results [CI]"
          git push
